version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra_secret
      POSTGRES_DB: sentinel
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

